### ISSUE TITLE
What is your discord?

### ISSUE THREAD

**Issue by theblobscp** [Kiffolisk/kiffolisk#1]
The discord tag is kinda unclear lol

**Comment by ArezalGame89** [comment]
@Kiffolisk , He's got a point! fix your discord

**Comment by Kiffolisk** [comment]
Candela Matalogue#3371

**Comment by theblobscp** [comment]
Delay much?

**Comment by Kiffolisk** [comment]
yeha ik i was inactive for 590 years too busy with other projects

**Comment by theblobscp** [comment]
Respectable
